export const info = [ { id: 0,
  title: 'Web Design',
  description: 'HTML and Javascript Cheat Sheet for Site Designers',
  image_url: 'https://i.pinimg.com/736x/df/ab/a4/dfaba49d42825148c330fbea08a90673--computer-programming-computer-science.jpg',
  user: 'Jamie Thomson',
  username: 'brillbluejay',
  hashtag: 'scoop.it' },
{ id: 1,
  title: 'tech',
  description: 'javascript cheat sheet                                                                                                                                                      Mehr',
  image_url: 'https://i.pinimg.com/736x/29/19/00/2919006d261b52f76039de7943e9a949--jquery-cheat-sheet-javascript-cheat-sheet.jpg',
  user: 'Kwanchit Donsophon',
  username: 'kwanrockz',
  hashtag: 'cheatography.com' },
{ id: 2,
  title: 'Dnnxc',
  description: 'http://eloquentjavascript.net',
  image_url: 'https://i.pinimg.com/736x/47/2e/93/472e93e0a83b58aa3b7fabbce198de50--python-programming-open-book.jpg',
  user: 'Herminio Garcia',
  username: 'hermano360',
  hashtag: 'readwrite.com' },
{ id: 3,
  title: 'Programming',
  description: 'Why JavaScript is the Future of Programming [Infographic]',
  image_url: 'https://i.pinimg.com/736x/8b/2a/ae/8b2aae5268dcaf515582bd43bfd61936--markup-language-python-programming.jpg',
  user: 'John MacDonald',
  username: 'johnathanmacdon',
  hashtag: 'sitepoint.com' },
{ id: 4,
  title: 'Tech',
  description: 'Whether you\'re an avid jQuery developer or just someone who is starting out, this jQuery cheat sheet will help you out.',
  image_url: 'https://i.pinimg.com/736x/f8/87/7d/f8877de598d61b822ea75a8789b4658c--dot-org-leave-a-comment.jpg',
  user: 'Legendary Sphere',
  username: 'successlives',
  hashtag: 'websitesetup.org' },
{ id: 5,
  title: 'Programming',
  description: 'A developer named Yusheng has created an amazing infographic that shows the entire JavaScript language syntax into one single image.',
  image_url: 'https://i.pinimg.com/736x/c3/66/76/c36676e9df58f22c5e48ec1fc35fda99--programming-languages-javascript-infographic.jpg',
  user: 'Abdulwahhab Alzaidan',
  username: 'abdulwahhaba',
  hashtag: 'fossbytes.com' },
{ id: 6,
  title: 'Programming',
  description: 'javascript cheat sheet',
  image_url: 'https://i.pinimg.com/736x/34/d7/13/34d7134e5f92476cd0bb416840f1ee67--programming-languages-computer-programming.jpg',
  user: 'Alex Federovitch',
  username: 'alexfederovitch',
  hashtag: 'beaubieblossom1.tumblr.com' },
{ id: 7,
  title: 'Javascript',
  description: '¿Que framework de JavaScript elegir? AngularJS, Ember.js y Backbone.js',
  image_url: 'https://i.pinimg.com/736x/a4/ba/94/a4ba94ca16d4cda1f53cacaff7d1d3f7--web-design-and-development-software-development.jpg',
  user: 'Eric Schumann',
  username: 'ericschumann82',
  hashtag: 'hongkiat.com' },
{ id: 8,
  title: 'Web Development',
  description: '24 Websites to Keep Your Finger on the Pulse in Web Development',
  image_url: 'https://i.pinimg.com/736x/3d/01/43/3d0143178f40b5199a010e13ba997427--dezvoltare-web-websites-design.jpg',
  user: 'Bo Mårtensson',
  username: 'bmrtensson',
  hashtag: 'blog.udacity.com' },
{ id: 9,
  title: 'Test board, anyone?',
  description: 'Should You Learn Python, C, or Ruby to Be a Top Coder? (Infographic) | Inc.com',
  image_url: 'https://i.pinimg.com/736x/e4/b3/b4/e4b3b40467ceabafd8e8a7b05140a039--coding-languages-languages-to-learn.jpg',
  user: 'Alexey Ugnichev',
  username: 'thaewrapt',
  hashtag: 'inc.com' },
{ id: 10,
  title: 'Dev Things',
  description: 'A look at node.js, server side framework that continues to gain popularity.',
  image_url: 'https://i.pinimg.com/736x/f0/27/54/f027547e96dea36f0869831ee7491621--getting-to-know-web-development.jpg',
  user: 'Jérémi Le Bourhis',
  username: 'jeremlb',
  hashtag: 'venturebeat.com' },
{ id: 11,
  title: 'jquery chuletas',
  description: 'jQuery-Cheat-Sheet. (Grafik: MakeAWebsiteHub.com)',
  image_url: 'https://i.pinimg.com/736x/be/19/3a/be193a25084803888935366a24acf916--javascript-code-javascript-cheat-sheet.jpg',
  user: 'Pablo Alvarez',
  username: 'pabloalvarezcor',
  hashtag: 't3n.de' },
{ id: 12,
  title: 'Html5Cheat sheets',
  description: 'Cheat-Sheet für HTML5-Entwickler. (Grafik: MakeAWebsiteHub.com )…',
  image_url: 'https://i.pinimg.com/736x/8e/a2/d5/8ea2d503e5172404adcc48e08003a695--web-knowledge-domain-knowledge.jpg',
  user: 'Arpit Kashyap',
  username: 'arpitkashyap',
  hashtag: 't3n.de' },
{ id: 13,
  title: 'Tecnologia',
  description: 'Top 7 Javacript Frameworks',
  image_url: 'https://i.pinimg.com/736x/bd/74/28/bd7428f50f939b5a4394c444f441f8c1--javascript-coding.jpg',
  user: 'Davide Pepe',
  username: 'davidepepe',
  hashtag: 'dzone.com' },
{ id: 14,
  title: 'Programmation',
  description: 'If you\'re looking to learn a programming language that\'s cross-platform and easily accessible, Java is one of the most practical languages out there. This handy cheat sheet helps you keep track of the basics while you begin to learn.',
  image_url: 'https://i.pinimg.com/736x/4d/d4/80/4dd480fcce8218568fd05aa3909bca56--game-programming-computer-programming.jpg',
  user: 'AbdülmouGhit Mansouri',
  username: 'gameover9',
  hashtag: 'lifehacker.com' },
{ id: 15,
  title: 'Web Resources',
  description: 'Web Animation Infographics: A Map of the Best Animation Libraries for JavaScript and CSS3 plus Performance Tips  Libraries, Frameworks, Plugins, and Performance Tips to Animate DOM Elements, UI, Canvas, and SVG',
  image_url: 'https://i.pinimg.com/736x/6c/21/ba/6c21baba43ca2f417876b13c0e616b30--best-animation-svg-animation.jpg',
  user: 'Taufan Erfiyanto',
  username: 'taufan20',
  hashtag: 'awwwards.stfi.re' },
{ id: 16,
  title: 'Programming',
  description: '#AngularJs Vs #ReactJs : Choosing Right the Framework   As a leading AngularJS development company iFlair provide you AngularJS development services and solutions as per your business needs at very affordable cost.  #infrographics #infographicsdesign',
  image_url: 'https://i.pinimg.com/736x/c1/18/97/c11897d653e9b1a9234981f63ae63399--angularjs-computer-science.jpg',
  user: 'Patric Rivera',
  username: 'patric25',
  hashtag: 'iflair.com' },
{ id: 17,
  title: 'web',
  description: 'Useful JavaScript Animation Plugins and Libraries',
  image_url: 'https://i.pinimg.com/736x/a3/a6/92/a3a69210214af287060dfaddf917355d--animation-programs-website-template.jpg',
  user: 'Chelsea Lee',
  username: 'talkingsheep',
  hashtag: 'downgraf.com' },
{ id: 18,
  title: 'Amo',
  description: 'JavaScript Cheatsheet. So glad I found this!http://www.addedbytes.com/cheat-sheets/javascript-cheat-sheet/',
  image_url: 'https://i.pinimg.com/736x/24/12/d5/2412d5d26bd713cf947703fce3bab617--computer-programming-computer-science.jpg',
  user: 'A Kapoor',
  username: 'kapooranuj',
  hashtag: 'hongkiat.com' },
{ id: 19,
  title: 'Web Design Inspiration',
  description: 'css3 cheat sheet',
  image_url: 'https://i.pinimg.com/736x/c9/ac/b4/c9acb422ced6c6b050a3fb3ccceb532e--html-code-html-css-javascript.jpg',
  user: 'Alex Knight',
  username: 'alexyahoo',
  hashtag: 'genautica.com' },
{ id: 20,
  title: 'Code',
  description: 'Lean HTML CSS JavaScript web programming. Free e-book from lukefabish.com',
  image_url: 'https://i.pinimg.com/736x/62/c5/b2/62c5b2b1c98e320dba4e0332578e7e7a--web-free-html-css.jpg',
  user: 'Cristina Estévez Rodríguez',
  username: 'cristinaestrod',
  hashtag: 'lukefabish.lpages.co' },
{ id: 21,
  title: 'Web Design and Development',
  description: '65+ Best Free Javascript Tutorials, PDF &amp; eBooks For Web Developers | FromDev',
  image_url: 'https://i.pinimg.com/736x/ff/10/28/ff102874369e87bbe8839b329ae400bc--coding-tutorials-free-tutorials.jpg',
  user: 'Andrew Carson',
  username: 'ACarsonDesign',
  hashtag: 'fromdev.com' },
{ id: 22,
  title: 'Coding',
  description: 'jQuery 1.6 cheat sheet #ESISsrl @Emily Sis S.r.l. Official Pinterest Page',
  image_url: 'https://i.pinimg.com/736x/b2/de/7c/b2de7cdae3ed82c8c24e9214bbdb8106--programming-languages-java-programming.jpg',
  user: 'Dibesh Maharjan',
  username: 'dibeshm',
  hashtag: 'Uploaded by user' },
{ id: 23,
  title: 'JavaScript',
  description: 'Node.js Joins the New Relic Family',
  image_url: 'https://i.pinimg.com/736x/a8/6d/e2/a86de26e1835475fe59c0d425cf961b7--programming-languages-computer-programming.jpg',
  user: 'Travis Choma',
  username: 'travischoma',
  hashtag: 'blog.newrelic.com' },
{ id: 24,
  title: 'New Tech',
  description: 'Frontend Vs Backend Dev!                                                                                                                                                      More',
  image_url: 'https://i.pinimg.com/736x/45/00/66/450066499345f589982eab30e2b81110--front-end-development-application-development.jpg',
  user: 'PLAS Technology',
  username: 'wade9606',
  hashtag: 'plas.biz' } ];